title: Trissie Development Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://cstate.mnts.lt'
params:
  alwaysKeepBrandColor: true
  brand: '#e83e8c'
  categories:
    - name: Main Systems
    - closed: true
      name: Services
    - closed: false
      description: Bot Statuses Will Display Here
      name: Bots
    - closed: true
      name: Servers
      untited: true
  customTabs:
    - link: 'https://trissidevelopment.com'
      name: Trissie Development Website
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /img/906FB21C-0BF5-4FEA-B437-D43409124FBD.jpeg
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - category: Our Main Gateway Is Cruicial For Our Services
      description: Main Systems
      name: Gateway
    - category: Main Systems
      description: Our Backup Gateway incase our Main Gateway Fails.
      name: Backup Gateway
    - category: Main Systems
      description: 'Our API Status, For Our Systems Functions'
      name: API
    - category: Main Systems
      description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      name: Media Proxy
    - category: Bots
      description: The Status Of Leopard Bot On Discord
      name: Leopard Bot
    - category: Servers
      name: 'EU West '
    - category: Servers
      name: EU Central
    - category: Servers
      description: ''
      name: US East
    - category: Servers
      name: US West
    - category: Servers
      name: 'US Central '
    - category: Services
      description: Status Of trissieimagehosting.ga
      name: Trissie Image Hosting
    - category: Services
      description: Status Of trissiesfiles.ga
      name: Trissie's File Server
    - category: Bots
      description: Status Of Discord Bot Trisbot
      name: Trisbot
    - category: Bots
      description: Status Of Discord Bot Spectro
      name: Spectro
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
